# Generated by Django 5.2.12 on 2026-03-23 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("bso", "BSO"),
                            ("kdv", "KDV / Kinderdagverblijf"),
                            ("gastouder", "Gastouderbureau"),
                            ("peuterspeelzaal", "Peuterspeelzaal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("house_number", models.CharField(blank=True, max_length=10)),
                ("postcode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "available_spots",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                (
                    "lrk_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("lrk_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_claimed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
