# Generated by Django 5.2.12 on 2026-03-25 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="gemeente",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institution",
            name="kvk_nummer_houder",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="institution",
            name="lrk_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="naam_houder",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="institution",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="institutions.institution",
            ),
        ),
    ]
