# Generated by Django 5.2.12 on 2026-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diplomacheck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diploma",
            name="bso_status",
            field=models.CharField(
                choices=[
                    ("direct", "Direct bevoegd"),
                    ("proof_required", "Bevoegd met aanvullend bewijs"),
                    ("not_qualified", "Niet bevoegd"),
                ],
                default="not_qualified",
                help_text="Kwalificatiestatus voor BSO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diploma",
            name="kdv_status",
            field=models.CharField(
                choices=[
                    ("direct", "Direct bevoegd"),
                    ("proof_required", "Bevoegd met aanvullend bewijs"),
                    ("not_qualified", "Niet bevoegd"),
                ],
                default="not_qualified",
                help_text="Kwalificatiestatus voor KDV / Dagopvang",
                max_length=20,
            ),
        ),
    ]
