# Generated by Django 5.2.12 on 2026-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("fulltime", "Full-time"),
                    ("parttime", "Part-time"),
                    ("temp", "Tijdelijk"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("assistent_pm", "Assistent pedagogisch medewerker"),
                    ("pm3", "Pedagogisch medewerker (niveau 3)"),
                    ("pm4", "Pedagogisch medewerker (niveau 4)"),
                    ("senior_pm", "Senior pedagogisch medewerker"),
                    ("bso_begeleider", "Groepsbegeleider BSO"),
                    ("coordinator_bso", "Coördinator BSO"),
                    ("teamleider", "Teamleider kinderopvang"),
                    ("locatiemanager", "Locatiemanager / Vestigingsmanager"),
                    ("beleidsmedewerker", "Pedagogisch beleidsmedewerker"),
                    ("gastouder", "Gastouder"),
                    ("nanny", "Nanny"),
                    ("stagiair", "Stagiair (BBL/BOL)"),
                ],
                max_length=30,
            ),
        ),
    ]
