# Generated by Django 5.2.12 on 2026-03-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_add_cao_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="min_experience",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="requires_bevoegdheid",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
