# Generated by Django 5.2.12 on 2026-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_scraping_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="geocodedlocation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fulltime", "Full-time"),
                    ("parttime", "Part-time"),
                    ("temp", "Tijdelijk"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assistent_pm", "Assistent pedagogisch medewerker"),
                    ("pm3", "Pedagogisch medewerker (niveau 3)"),
                    ("pm4", "Pedagogisch medewerker (niveau 4)"),
                    ("senior_pm", "Senior pedagogisch medewerker"),
                    ("bso_begeleider", "Groepsbegeleider BSO"),
                    ("coordinator_bso", "Coördinator BSO"),
                    ("teamleider", "Teamleider kinderopvang"),
                    ("locatiemanager", "Locatiemanager / Vestigingsmanager"),
                    ("beleidsmedewerker", "Pedagogisch beleidsmedewerker"),
                    ("gastouder", "Gastouder"),
                    ("nanny", "Nanny"),
                    ("stagiair", "Stagiair (BBL/BOL)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="vacatureclick",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
