# Generated by Django 5.2.12 on 2026-04-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_vestiging"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
