# Generated by Django 5.2.12 on 2026-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="bevoegdheid",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="hours_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="house_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="immediate_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="postcode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
