# Generated by Django 5.2.12 on 2026-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_bevoegdheid_hours_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="cao_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assistent_pm", "Assistent pedagogisch medewerker"),
                    ("pm3", "Pedagogisch medewerker (niveau 3)"),
                    ("pm4", "Pedagogisch medewerker (niveau 4)"),
                    ("senior_pm", "Senior pedagogisch medewerker"),
                    ("bso_begeleider", "Groepsbegeleider BSO"),
                    ("coordinator_bso", "Coördinator BSO"),
                    ("teamleider", "Teamleider kinderopvang"),
                    ("locatiemanager", "Locatiemanager / Vestigingsmanager"),
                    ("beleidsmedewerker", "Pedagogisch beleidsmedewerker"),
                    ("gastouder", "Gastouder"),
                    ("nanny", "Nanny"),
                    ("stagiair", "Stagiair (BBL/BOL)"),
                ],
                max_length=30,
            ),
        ),
    ]
