# Generated by Django 5.2.12 on 2026-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_cao_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="bso_proof_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="kdv_proof_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="opvangtype",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
