"""
Erkende diploma's voor de kinderopvang sector (CAO Kinderopvang).
Bron: CAO Kinderopvang bijlage 13 — diplomalijst kwalificerende functies.

kdv_status / bso_status:
  "direct"        → direct bevoegd (A1 / B1)
  "proof_required"→ bevoegd met aanvullend bewijs (A2 / B2)
  "not_qualified" → niet bevoegd
"""

DIPLOMA_DATA = [
    # ══════════════════════════════════════════════════════════════════════════
    # MBO NIVEAU 2
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Helpende Zorg & Welzijn",
        "crebo": "25491",
        "level": "mbo2",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["assistent_pm"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Directe kwalificatie als assistent pedagogisch medewerker. Werkt altijd onder begeleiding van een bevoegd PM.",
    },
    {
        "name": "Helpende Welzijn (oud)",
        "crebo": "10760",
        "level": "mbo2",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["assistent_pm"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Oud CREBO-nummer, nog steeds erkend onder CAO Kinderopvang.",
    },
    {
        "name": "Verzorgende (oud, MBO niveau 2)",
        "crebo": "10760",
        "level": "mbo2",
        "kdv_status": "proof_required",
        "bso_status": "not_qualified",
        "qualifying_roles": ["assistent_pm"],
        "qualifying_institution_types": ["kdv"],
        "notes": "A2 — Kwalificeert als assistent PM in KDV met aanvullend bewijs van pedagogische competenties.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # MBO NIVEAU 3
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Medewerker Kinderopvang",
        "crebo": "25696",
        "level": "mbo3",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm3", "bso_begeleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Directe kwalificatie voor pedagogisch medewerker niveau 3. Primaire opleiding voor de kinderopvang.",
    },
    {
        "name": "Sociaal Pedagogisch Werker (SPW, oud)",
        "crebo": "10417",
        "level": "mbo3",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm3", "bso_begeleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Oud diploma, voorloper van Medewerker Kinderopvang. Volledig erkend onder CAO Kinderopvang.",
    },
    {
        "name": "Gezelschapsleider (oud)",
        "crebo": "10416",
        "level": "mbo3",
        "kdv_status": "not_qualified",
        "bso_status": "direct",
        "qualifying_roles": ["bso_begeleider", "pm3"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B1 — Erkend voor BSO en peuterspeelzaal. Niet kwalificerend voor KDV.",
    },
    {
        "name": "Activiteitenbegeleider (oud)",
        "crebo": "10415",
        "level": "mbo3",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["bso_begeleider"],
        "qualifying_institution_types": ["bso"],
        "notes": "B2 — Erkend voor BSO met aanvullende kinderopvangscholing.",
    },
    {
        "name": "Medewerker Sociaal-Cultureel Werk (MSCW, oud)",
        "crebo": "10494",
        "level": "mbo3",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["bso_begeleider"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B2 — Kwalificeert voor BSO met aanvullend bewijs van pedagogische competenties.",
    },
    {
        "name": "Sport en Bewegen (niveau 3)",
        "crebo": "25408",
        "level": "mbo3",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["bso_begeleider"],
        "qualifying_institution_types": ["bso"],
        "notes": "B2 — Kwalificeert voor BSO met bewegingsgericht programma. Aanvullende kinderopvangscholing vereist.",
    },
    {
        "name": "Helpende Plus (oud MBO3)",
        "crebo": "10761",
        "level": "mbo3",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["assistent_pm"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Oud diploma. Kwalificeert als assistent PM.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # MBO NIVEAU 4
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Pedagogisch Werk",
        "crebo": "25697",
        "level": "mbo4",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "pm3", "bso_begeleider", "coordinator_bso"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Directe kwalificatie voor pedagogisch medewerker niveau 4.",
    },
    {
        "name": "Gespecialiseerd Pedagogisch Medewerker (GPM, oud)",
        "crebo": "92640",
        "level": "mbo4",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "pm3", "bso_begeleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Oud CREBO. Voorloper van Pedagogisch Werk niveau 4. Volledig erkend.",
    },
    {
        "name": "Sociaal Pedagogisch Werker (SPW niveau 4, oud)",
        "crebo": "10418",
        "level": "mbo4",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "pm3", "bso_begeleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Oud diploma. Volledig erkend als PM4 onder CAO Kinderopvang.",
    },
    {
        "name": "Sociaal Werk",
        "crebo": "25480",
        "level": "mbo4",
        "kdv_status": "proof_required",
        "bso_status": "proof_required",
        "qualifying_roles": ["pm4", "bso_begeleider", "coordinator_bso"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A2 — Kwalificeert voor PM4 en BSO met aanvullende scholing specifiek voor kinderopvang (minimaal 240 uur).",
    },
    {
        "name": "Onderwijsassistent",
        "crebo": "25187",
        "level": "mbo4",
        "kdv_status": "not_qualified",
        "bso_status": "direct",
        "qualifying_roles": ["bso_begeleider", "coordinator_bso", "pm3"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B1 — Directe kwalificatie voor BSO en peuterspeelzaal. Niet zelfstandig inzetbaar in KDV.",
    },
    {
        "name": "Onderwijsassistent (oud)",
        "crebo": "91670",
        "level": "mbo4",
        "kdv_status": "not_qualified",
        "bso_status": "direct",
        "qualifying_roles": ["bso_begeleider", "coordinator_bso"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B1 — Oud CREBO. Erkend voor BSO en peuterspeelzaal.",
    },
    {
        "name": "Maatschappelijke Zorg",
        "crebo": "25481",
        "level": "mbo4",
        "kdv_status": "proof_required",
        "bso_status": "proof_required",
        "qualifying_roles": ["pm4"],
        "qualifying_institution_types": ["kdv", "bso"],
        "notes": "A2 — Kwalificeert voor PM4 met aanvullende kinderopvangscholing. Afhankelijk van specialisatierichting.",
    },
    {
        "name": "Verpleegkunde (MBO niveau 4)",
        "crebo": "25478",
        "level": "mbo4",
        "kdv_status": "proof_required",
        "bso_status": "not_qualified",
        "qualifying_roles": ["pm4"],
        "qualifying_institution_types": ["kdv"],
        "notes": "A2 — Erkend voor KDV, met name voor baby- en dreumesgroepen. Aanvullende kinderopvangmodules vereist.",
    },
    {
        "name": "Sport en Bewegen (niveau 4)",
        "crebo": "25409",
        "level": "mbo4",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["bso_begeleider", "coordinator_bso"],
        "qualifying_institution_types": ["bso"],
        "notes": "B2 — Kwalificeert voor BSO met bewegingsgericht programma. Aanvullende kinderopvangscholing vereist.",
    },
    {
        "name": "Pedagogisch Medewerker Kinderopvang (PMK, oud)",
        "crebo": "92630",
        "level": "mbo4",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "pm3", "bso_begeleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Oud CREBO. Erkend als PM4 onder CAO Kinderopvang.",
    },
    {
        "name": "Welzijn (niveau 4, oud)",
        "crebo": "10493",
        "level": "mbo4",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["pm4", "bso_begeleider"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B2 — Oud diploma. Kwalificeert met aanvullend bewijs voor BSO.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # HBO
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Social Work (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm", "teamleider", "coordinator_bso", "beleidsmedewerker"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal", "gastouder"],
        "notes": "A1 — Brede HBO-kwalificatie erkend voor alle uitvoerende en coördinerende functies.",
    },
    {
        "name": "Maatschappelijk Werk en Dienstverlening (MWD)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm", "beleidsmedewerker"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Erkend HBO-diploma voor PM4 en senior functies in de kinderopvang.",
    },
    {
        "name": "Sociaal-Pedagogische Hulpverlening (SPH)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm", "beleidsmedewerker", "teamleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Directe kwalificatie voor PM4 en senior PM. Breed erkend in de kinderopvang.",
    },
    {
        "name": "Culturele en Maatschappelijke Vorming (CMV)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "proof_required",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "bso_begeleider", "coordinator_bso"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B1/A2 — Directe kwalificatie voor BSO. Aanvullende scholing vereist voor KDV.",
    },
    {
        "name": "Pedagogiek (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm", "beleidsmedewerker", "teamleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — HBO Pedagogiek kwalificeert direct voor PM4 en hoger.",
    },
    {
        "name": "PABO / Leraar Basisonderwijs (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "proof_required",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm", "bso_begeleider", "coordinator_bso"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B1/A2 — Directe kwalificatie voor BSO en peuterspeelzaal. Aanvullende kinderopvangscholing aanbevolen voor KDV.",
    },
    {
        "name": "Leraar Speciaal Onderwijs (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "not_qualified",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm", "bso_begeleider"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B1 — Erkend voor BSO en peuterspeelzaal. Niet als zelfstandige kwalificatie voor KDV.",
    },
    {
        "name": "Verpleegkunde (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "direct",
        "bso_status": "not_qualified",
        "qualifying_roles": ["pm4", "senior_pm"],
        "qualifying_institution_types": ["kdv"],
        "notes": "A1 — Erkend voor KDV. Met name geschikt voor baby- en dreumesgroepen en medisch-gericht werk.",
    },
    {
        "name": "Psychomotorische Therapie en Bewegingsagogie (PMTB / HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "not_qualified",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "bso_begeleider"],
        "qualifying_institution_types": ["bso"],
        "notes": "B1 — Kwalificeert voor BSO met bewegings- of therapiegericht programma.",
    },
    {
        "name": "Creatieve Therapie (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["pm4"],
        "qualifying_institution_types": ["bso", "peuterspeelzaal"],
        "notes": "B2 — Kwalificeert voor BSO en peuterspeelzaal mits aanvullende kinderopvangscholing gevolgd.",
    },
    {
        "name": "Fysiotherapie (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["pm4"],
        "qualifying_institution_types": ["bso"],
        "notes": "B2 — Kwalificeert voor BSO met bewegingsgericht programma. Aanvullende kinderopvangscholing vereist.",
    },
    {
        "name": "Leraar Lichamelijke Opvoeding (ALO / HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["bso_begeleider", "pm4"],
        "qualifying_institution_types": ["bso"],
        "notes": "B2 — Erkend voor BSO met sportgericht aanbod. Aanvullend bewijs pedagogische competenties kinderopvang vereist.",
    },
    {
        "name": "Psychologie (HBO Bachelor)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "proof_required",
        "bso_status": "proof_required",
        "qualifying_roles": ["beleidsmedewerker"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A2 — Kwalificeert als pedagogisch beleidsmedewerker. Aanvullende kinderopvangscholing vereist.",
    },
    {
        "name": "Sociaal Juridische Dienstverlening (SJD / HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "proof_required",
        "bso_status": "proof_required",
        "qualifying_roles": ["beleidsmedewerker"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A2 — Kwalificeert als beleidsmedewerker met aanvullende kinderopvangscholing.",
    },
    {
        "name": "Docent Gezondheidszorg en Welzijn (2e graad, HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["pm4", "senior_pm"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Erkend HBO-opleiding voor pedagogisch medewerker niveau 4.",
    },
    {
        "name": "Sportkunde / Human Movement Sciences (HBO)",
        "crebo": "",
        "level": "hbo",
        "kdv_status": "not_qualified",
        "bso_status": "proof_required",
        "qualifying_roles": ["bso_begeleider"],
        "qualifying_institution_types": ["bso"],
        "notes": "B2 — Kwalificeert voor BSO met bewegingsgericht programma na aanvullende kinderopvangscholing.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # WO / MASTER
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Pedagogische Wetenschappen (WO / Master)",
        "crebo": "",
        "level": "wo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["senior_pm", "beleidsmedewerker", "teamleider", "locatiemanager"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal", "gastouder"],
        "notes": "A1 — Academische kwalificatie erkend voor alle senior en managementfuncties.",
    },
    {
        "name": "Orthopedagogiek (WO / Master)",
        "crebo": "",
        "level": "wo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["senior_pm", "beleidsmedewerker", "teamleider"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Erkend voor senior en beleidsfuncties in de kinderopvang.",
    },
    {
        "name": "Psychologie (WO / Master)",
        "crebo": "",
        "level": "wo",
        "kdv_status": "proof_required",
        "bso_status": "proof_required",
        "qualifying_roles": ["beleidsmedewerker", "senior_pm"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A2 — Kwalificeert als pedagogisch beleidsmedewerker met aanvullende kinderopvangscholing.",
    },
    {
        "name": "Onderwijskunde (WO / Master)",
        "crebo": "",
        "level": "wo",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["beleidsmedewerker", "senior_pm"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — Erkend voor beleid en senior functies in de kinderopvang.",
    },
    {
        "name": "Sociale Wetenschappen (WO / Master)",
        "crebo": "",
        "level": "wo",
        "kdv_status": "proof_required",
        "bso_status": "proof_required",
        "qualifying_roles": ["beleidsmedewerker"],
        "qualifying_institution_types": ["kdv", "bso", "peuterspeelzaal"],
        "notes": "A2 — Kwalificeert als beleidsmedewerker na aanvullende scholing in kinderopvang.",
    },
    {
        "name": "Geneeskunde / Kindergeneeskunde (WO / Master)",
        "crebo": "",
        "level": "wo",
        "kdv_status": "proof_required",
        "bso_status": "not_qualified",
        "qualifying_roles": ["beleidsmedewerker", "senior_pm"],
        "qualifying_institution_types": ["kdv"],
        "notes": "A2 — Erkend voor KDV als beleidsmedewerker of senior PM na aanvullende kinderopvangscholing.",
    },

    # ══════════════════════════════════════════════════════════════════════════
    # GASTOUDER-SPECIFIEK
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Gastouderattest / Basiscursus Gastouderopvang",
        "crebo": "",
        "level": "mbo2",
        "kdv_status": "not_qualified",
        "bso_status": "not_qualified",
        "qualifying_roles": ["gastouder"],
        "qualifying_institution_types": ["gastouder"],
        "notes": "Verplichte basiskwalificatie voor gastouders via erkend gastouderbureau. Niet geldig voor KDV of BSO.",
    },
    {
        "name": "Medewerker Kinderopvang (gastouder via MBO3)",
        "crebo": "25696",
        "level": "mbo3",
        "kdv_status": "direct",
        "bso_status": "direct",
        "qualifying_roles": ["gastouder", "pm3"],
        "qualifying_institution_types": ["gastouder", "kdv", "bso", "peuterspeelzaal"],
        "notes": "A1 — MBO3 Medewerker Kinderopvang kwalificeert ook als gastouder via een gastouderbureau.",
    },
]
